site_name: Django Lifecycle Hooks

theme:
  name: "material"
  language: en
  feature:
    tabs: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: green
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo:
    icon: "cached"
repo_name: rsinger86/django-lifecycle
repo_url: https://github.com/rsinger86/django-lifecycle

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Examples: examples.md
  - Lifecycle Moments & Conditions: hooks_and_conditions.md
  - Watching ForeignKey Changes: fk_changes.md
  - Advanced: advanced.md
